### ISSUE TITLE
Error while launching the Boot agent in SARL

### ISSUE THREAD

**Issue by chachem97** [sarl/sarl#962] opened 2020-01-27 19:34 UTC
Hello,

I have cloned an already existed project from github into SARL and tried to run the BootAgent. 

The issue is I am getting the following error:
Error: Could not find or load main class io.janusproject.Boot
Caused by: java.lang.ClassNotFoundException: io.janusproject.Boot

However, if you try to run the configuration you will get this error as well: 
"Undefined agent io.sarl.airsim.BootAgent"

Could you please help me in order to solve this issue because I need to run this project in order to see the simulation in AirSim.

Regards,

Hachem

**Comment by gallandarakhneorg** [comment] 2020-01-28 08:36
Duplicate of #963

**Closed by gallandarakhneorg** 2020-01-28 08:36 UTC
Labels: duplicate
