### ISSUE TITLE
Inability to run the BootAgent 

### ISSUE THREAD

**Issue by charbelmansour** [sarl/sarl#961] opened 2020-01-22 16:31 UTC
We cloned the project https://github.com/alexandrelombard/sarl-airsim-interface.git and we tried to run the BootAgent. We used run as "SarlAgent" but we obtained this error:

Error when launching Janus: Broken URL: file:C:\SPB_Data\git\sarl-airsim-interface\src\main\sarl\io\sarl\airsim/

Note that we tried to run a project that we made in the same way and it worked.

Thank you for your help.
Regards,
Charbel

**Comment by gallandarakhneorg** [comment] 2020-01-23 12:37
The URL "file:C:\SPB_Data\git\sarl-airsim-interface\src\main\sarl\io\sarl\airsim/" is not a valid URL according to international standards.
It must be "file://C:/SPB_Data/git/sarl-airsim-interface/src/main/sarl/io/sarl/airsim/".

We will explore into the SARL product in order to determine if the fact that you run a Windows box causes the Eclipse RCP to build an invalid URL or if the problem is in the SARL code.

**Comment by charbelmansour** [comment] 2020-01-23 15:33
Okay, Thank you.
Please keep us updated with any news about this issue.
Regards,
Charbel

**Comment by gallandarakhneorg** [comment] 2020-01-31 06:55
This error will be fixed for the next coming release, in march 2020.

**Comment by gallandarakhneorg** [comment] 2020-03-20 14:32
This issue seems to exist on Windows OS only.

**Comment by gallandarakhneorg** [comment] 2020-03-30 18:39
Cannot reproduce this issue on a Windows 10 box with JDK Zulu 1.8. See Issue #991 for the details of the last changes.

**Closed by gallandarakhneorg** 2020-03-30 18:39 UTC
Labels: 2 - In progress, Eclipse, bug, invalid
