### ISSUE TITLE
Sporious error on ECLIPSE IDE  on capacity/skill

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#1055] opened 2021-02-07 23:21 UTC
**Describe the bug**

When compiling from ECLIPSE it says:

```
Invalid implemented type: 'io.sarl.extras.KB_Prolog'. Only subtypes of 'io.sarl.lang.core.Capacity' are allowed for 'SWIJPL_KB_Prolog'.	SWIJPL_KB_Prolog.sarl	/sarl-prolog-cap/src/main/sarl/io/sarl/extras	
```

but that is wrong, everything is fine in that skill `io.sarl.extras.KB_Prolog':

```
skill SWIJPL_KB_Prolog implements KB_Prolog {
```

I open the file of the skill, compile, and error is gone on the IDE!

**To Reproduce**

1. Compile from scratch (error shows up)
2. Open skill
3. Compile again (error is gone)

**Expected behavior**

There should be no complain on the skill...

**Screenshots**

![image](https://user-images.githubusercontent.com/2368384/107162404-ed5b7f80-69f6-11eb-8962-49e088013f62.png)

**System configuration:**
-- SARL version:	0.11.0
-- SARL compiler:	
-  - [] Eclipse compiler without Maven	
-  - [X ] Eclipse compiler with Maven	
-  - [ ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name):	
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Windows 64bits	
-  - [ ] MacOS 64bits	

**Additional context**

**Comment by gallandarakhneorg** [comment] 2021-02-08 08:39
Dear @ssardina.

This type of error may occur when the version of the SARL API into the Eclipse IDE is different than the version of SARL included into the project.

So, before doing a complete diagnostic, could you confirm that the version into the POM file is '0.11.0' for SARL and '3.0.11.0' for Janus (if you use it).

**Comment by ssardina** [comment] 2021-02-09 05:23
It does have 0.11.0 in the `pom.xml`:

![image](https://user-images.githubusercontent.com/2368384/107319466-00ec1080-6af3-11eb-9b14-752194b9327a.png)

It compiles perfectly in the CLI.

As I said, if I open the file and compile it, errors goes away...

**Comment by ssardina** [comment] 2021-02-09 05:23
Of course, for completeness:

![image](https://user-images.githubusercontent.com/2368384/107319591-33960900-6af3-11eb-85a9-511c6811d3e2.png)

**Comment by gallandarakhneorg** [comment] 2021-02-09 07:30
You're issue seems to be related to the issue [49](https://github.com/eclipse/xtext-lib/issues/49) of Xtext Lib.

Duplicate of #661 and related also to #331.

**Closed by gallandarakhneorg** 2021-02-09 07:30 UTC
Labels: Eclipse, Language & Compiler, bug, duplicate
