### ISSUE TITLE
Create SARL Debug perspective and associated debug views

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#430] opened 2016-06-28 14:13 UTC
Add specific views for the SARL debugging such as:
* Hierarchy of agents/holons
* Sending event to running agents

**Comment by gallandarakhneorg** [comment] 2016-06-28 14:49
:+1:

**Comment by gallandarakhneorg** [comment] 2016-06-29 16:10
This is not a duplicate of #142. Indeed this issue is for a "debugging/run-time" perspective; and Issue #146 is for a "developer" perspective.

**Closed** 2016-08-24 14:54 UTC
Labels: 2 - Working, Eclipse
