### ISSUE TITLE
No Janus SRE for pre-configured Eclipse with SARL SDK 0.11.0 and Java 11

### ISSUE THREAD

**Issue by JonathanSamelson** [sarl/sarl#1012] opened 2020-06-17 15:02 UTC
**Describe the bug**
I downloaded pre-configured Eclipse with SARL SDK version 0.11.0. I opened "A Hello World Agent in SARL" but I could not execute it because there is no Janus SRE configured in this version.

**To Reproduce**
0. Download pre-configured Eclipse with SARL SDK 0.11.0
1. Open a SARL project (tried with "hello world" and "two simple agents in basic interaction")
2. Go to Window > Preferences > SARL > Installed SREs
3. There is no SRE
4. Try to add the SRE with the jar file "io.janusproject.kernel-3.0.11.0-with-dependencies.jar" found on Maven Central
5. See screenshot below

**Expected behavior**
Like in version 0.10.1, I expect to have the Janus SRE configured and ready to run.

**Screenshots**
![image](https://user-images.githubusercontent.com/19322574/84913785-2edf9900-b0bb-11ea-8969-e4dd3074e89a.png)

**System configuration:**
-- SARL version:	0.11.0
-- SARL compiler:	
-  - [x] Eclipse compiler without Maven	
-  - [ ] Eclipse compiler with Maven	
-  - [ ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name):	11.0.7
-- Operating System:	
-  - [ ] Linux 64bits	
-  - [x] Windows 64bits	
-  - [ ] MacOS 64bits	

**Additional context**

**Comment by gallandarakhneorg** [comment] 2020-06-17 15:23
Thank you for finding this issue. This is a major issue. It will be fixed during the coming days. A new release will be published: 0.11.1

**Comment by ngaud** [comment] 2020-06-17 16:12
Effectively I was able to reproduce the corresponding error on Windows 10 with jdk 11

!SESSION 2020-06-17 18:06:02.025 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.7
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY io.janusproject.eclipse 4 0 2020-06-17 18:06:11.839
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: io.janusproject.eclipse [24]
  Unresolved requirement: Require-Bundle: io.janusproject.plugin; bundle-version="0.11.0"; visibility:="reexport"
    -> Bundle-SymbolicName: io.janusproject.plugin; bundle-version="0.11.0"; singleton:="true"
       io.janusproject.plugin [25]
         Unresolved requirement: Require-Bundle: com.fasterxml.jackson.module.jackson-module-jaxb-annotations; bundle-version="2.10.1"
           -> Bundle-SymbolicName: com.fasterxml.jackson.module.jackson-module-jaxb-annotations; bundle-version="2.10.1"
              com.fasterxml.jackson.module.jackson-module-jaxb-annotations [9]
                Unresolved requirement: Import-Package: javax.activation; version="[1.2.0,2.0.0)"; resolution:="optional"
                Unresolved requirement: Import-Package: javax.xml.bind.annotation; version="[2.3.0,3.0.0)"
                  -> Export-Package: javax.xml.bind.annotation; bundle-symbolic-name="jakarta.xml.bind-api"; bundle-version="2.3.2"; version="2.3.2"; uses:="javax.xml.bind,javax.xml.parsers,javax.xml.transform,javax.xml.transform.dom,org.w3c.dom"
                     jakarta.xml.bind-api [38]
                       Unresolved requirement: Import-Package: javax.activation
                Unresolved requirement: Import-Package: javax.xml.bind; version="[2.3.0,3.0.0)"
                  -> Export-Package: javax.xml.bind; bundle-symbolic-name="jakarta.xml.bind-api"; bundle-version="2.3.2"; version="2.3.2"; uses:="javax.xml.bind.annotation.adapters,javax.xml.bind.attachment,javax.xml.namespace,javax.xml.stream,javax.xml.transform,javax.xml.validation,org.w3c.dom,org.xml.sax"
         Unresolved requirement: Require-Bundle: com.fasterxml.jackson.dataformat.jackson-dataformat-xml; bundle-version="2.10.1"
           -> Bundle-SymbolicName: com.fasterxml.jackson.dataformat.jackson-dataformat-xml; bundle-version="2.10.1"
              com.fasterxml.jackson.dataformat.jackson-dataformat-xml [7]
                Unresolved requirement: Import-Package: com.fasterxml.jackson.module.jaxb; version="[2.10.0,3.0.0)"
                  -> Export-Package: com.fasterxml.jackson.module.jaxb; bundle-symbolic-name="com.fasterxml.jackson.module.jackson-module-jaxb-annotations"; bundle-version="2.10.1"; version="2.10.1"; uses:="com.fasterxml.jackson.annotation,com.fasterxml.jackson.core,com.fasterxml.jackson.databind,com.fasterxml.jackson.databind.cfg,com.fasterxml.jackson.databind.introspect,com.fasterxml.jackson.databind.jsontype,com.fasterxml.jackson.databind.type,com.fasterxml.jackson.databind.util,javax.xml.bind.annotation,javax.xml.bind.annotation.adapters"

	at org.eclipse.osgi.container.Module.start(Module.java:462)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1844)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1837)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1778)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1742)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY io.janusproject.plugin 4 0 2020-06-17 18:06:12.184
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: io.janusproject.plugin [25]
  Unresolved requirement: Require-Bundle: com.fasterxml.jackson.module.jackson-module-jaxb-annotations; bundle-version="2.10.1"
    -> Bundle-SymbolicName: com.fasterxml.jackson.module.jackson-module-jaxb-annotations; bundle-version="2.10.1"
       com.fasterxml.jackson.module.jackson-module-jaxb-annotations [9]
         Unresolved requirement: Import-Package: javax.activation; version="[1.2.0,2.0.0)"; resolution:="optional"
         Unresolved requirement: Import-Package: javax.xml.bind.annotation; version="[2.3.0,3.0.0)"
           -> Export-Package: javax.xml.bind.annotation; bundle-symbolic-name="jakarta.xml.bind-api"; bundle-version="2.3.2"; version="2.3.2"; uses:="javax.xml.bind,javax.xml.parsers,javax.xml.transform,javax.xml.transform.dom,org.w3c.dom"
              jakarta.xml.bind-api [38]
                Unresolved requirement: Import-Package: javax.activation
         Unresolved requirement: Import-Package: javax.xml.bind; version="[2.3.0,3.0.0)"
           -> Export-Package: javax.xml.bind; bundle-symbolic-name="jakarta.xml.bind-api"; bundle-version="2.3.2"; version="2.3.2"; uses:="javax.xml.bind.annotation.adapters,javax.xml.bind.attachment,javax.xml.namespace,javax.xml.stream,javax.xml.transform,javax.xml.validation,org.w3c.dom,org.xml.sax"
  Unresolved requirement: Require-Bundle: com.fasterxml.jackson.dataformat.jackson-dataformat-xml; bundle-version="2.10.1"
    -> Bundle-SymbolicName: com.fasterxml.jackson.dataformat.jackson-dataformat-xml; bundle-version="2.10.1"
       com.fasterxml.jackson.dataformat.jackson-dataformat-xml [7]
         Unresolved requirement: Import-Package: com.fasterxml.jackson.module.jaxb; version="[2.10.0,3.0.0)"
           -> Export-Package: com.fasterxml.jackson.module.jaxb; bundle-symbolic-name="com.fasterxml.jackson.module.jackson-module-jaxb-annotations"; bundle-version="2.10.1"; version="2.10.1"; uses:="com.fasterxml.jackson.annotation,com.fasterxml.jackson.core,com.fasterxml.jackson.databind,com.fasterxml.jackson.databind.cfg,com.fasterxml.jackson.databind.introspect,com.fasterxml.jackson.databind.jsontype,com.fasterxml.jackson.databind.type,com.fasterxml.jackson.databind.util,javax.xml.bind.annotation,javax.xml.bind.annotation.adapters"

	at org.eclipse.osgi.container.Module.start(Module.java:462)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1844)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1837)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1778)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1742)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

**Comment by ngaud** [comment] 2020-06-17 16:13
The problem appears only with the JDK 11. We will quickly solved the problem.
In the meantime, if you change force SARL IDe to run on JDK 8, it works.

**Comment by gallandarakhneorg** [comment] 2020-06-17 16:34
@ngaud, Jackson was included only in order to export the live configuration of Janus to XML format. We could safely remove this feature since we have already the same feature for Json and Yaml output formats.

**Comment by gallandarakhneorg** [comment] 2020-06-17 19:10
It seems that several dependencies that are specified into the Janus plugin MANIFEST file are no more used into the code. I will clean the version 0.12, and we will be able to try on version 0.11.1.

**Comment by gallandarakhneorg** [comment] 2020-07-30 18:27
Compiling and running with Java 11 on the command line is working as expected. Except the standard warnings:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.databind.util.ClassUtil (file:/path/file.jar) to field java.util.logging.Level.name
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.databind.util.ClassUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

This issue should be solved when Issue #955 related to the move to Java 11 as the minimal Java version for SARL tools.

**Comment by gallandarakhneorg** [comment] 2020-07-30 19:01
Within the Eclipse SARL IDE, three different behaviors could be seen:

1. With a **SARL Agent** launch configuration: the following error is thrown : `java.lang.ClassNotFoundException: io.sarl.tests.dbg.TestAgent`
2. With a **SARL Application** launch configuration: the following error is thrown : `java.lang.ClassNotFoundException: io.sarl.tests.dbg.TestMain`
3. With a **Java Application** launch configuration: no error

Consequently, the SARL launch configuration API is not compatible with Java 11.

**Comment by gallandarakhneorg** [comment] 2020-08-17 08:32
The following configurations were tested:

| Java compiler version | JRE version | Interaction mode | State |
| ----------------------------- | ---------------- | ---------------------- | ------- |
| 8 | 8 | CLI | success |
| 8 | 11 | CLI | success |

**Comment by gallandarakhneorg** [comment] 2020-08-17 09:51
With JRE 11 in Eclipse, the following warning message is output on the console:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:path/com.google.inject_4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Closed** 2020-08-17 10:46 UTC
Labels: 2 - In progress, Eclipse, bug
