### ISSUE TITLE
Error when launching janus

### ISSUE THREAD

**Issue by chachem97** [sarl/sarl#965] opened 2020-01-29 20:33 UTC
Hello,

We are encountering an error when running the boot agent in Sarl.

The error is:
Error when launching Janus: Broken URL: file:C:\Users\Charbel\Documents\io.sarl.lang.updatesite-0.10.0-win32.win32.x86_64\sarl-airsim-interface-master/
Exception in thread "main" io.janusproject.Boot$ExitSignal
	at io.janusproject.Boot.lambda$1(Boot.java:1130)
	at io.janusproject.Boot.showVersion(Boot.java:774)
	at io.janusproject.Boot.showError(Boot.java:689)
	at io.janusproject.Boot.mainWithExitCode(Boot.java:526)
	at io.janusproject.Boot.main(Boot.java:484)

When we try to click on one of the exception thread we are getting this error also:
![image](https://user-images.githubusercontent.com/60363721/73394680-b7b19000-42e6-11ea-8908-23a299adc6fe.png)

However, we searched in all the codes and folders of the project for this URL in order to change it but we are not founding.

Note that we are working with windows 10 - 

The following project is the follow:

[sarl-airsim-interface-master.zip](https://github.com/sarl/sarl/files/4130582/sarl-airsim-interface-master.zip)

Thank you for helping us,

Regards,

chachem

**Comment by gallandarakhneorg** [comment] 2020-01-31 06:54
Duplicate of #961

**Closed by gallandarakhneorg** 2020-01-31 06:54 UTC
Labels: duplicate
