### ISSUE TITLE
Hazelcast 4.x support

### ISSUE THREAD

**Issue by JonathanSamelson** [sarl/sarl#1059] opened 2021-02-10 12:12 UTC
Hello, I've been encountering an issue when trying to move my solution to Hazelcast 4.x. Last time I used SARL it was with Hazelcast 3.12 as I needed to communicate with Python client that did not yet support version 4.
 
**Is your feature request related to a problem? Please describe.**
After a few hours trying to figure out where the problem actually was, I found out it happened only when starting my application from a SARL context. When running this sample code in Java, everything ran smoothly: 

```
public class TopicSample implements MessageListener<String> {
    @Override
    public void onMessage(Message<String> message) {
        System.out.println("Got message " + message.getMessageObject());
    }

    public static void main(String[] args) {
    	Config config = new Config();
        // Start the Embedded Hazelcast Cluster Member.
        HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);
        // Get a Topic called "my-distributed-topic"
        ITopic<String> topic = hz.getTopic("my-distributed-topic");
        // Add a Listener to the Topic
        topic.addMessageListener(new TopicSample());
        // Publish a message to the Topic
        topic.publish("Hello to distributed world");
        // Shutdown the Hazelcast Cluster Member
        hz.shutdown();
    }
}
```

However when I ran this equivalent agent, I got a problem when I try to get the hazelcast instance:

```
agent SimpleAgent {
	on Initialize {
		var hcConfig = new Config
		var hcInstance = Hazelcast.newHazelcastInstance()
		var topic = hcInstance.getTopic("test")
		topic.addMessageListener(new MessageListener<String>(){
			def onMessage(message : Message<String>) {
				println("Got message " + message.getMessageObject)
			}
			
		})
		topic.publish("Hello to distributed world")
		hcInstance.shutdown
		
	}
}
```

I get the following Stacktrace:
```
[SEVERE, 12:40:13pm, com.hazelcast.instance.impl.Node] [130.104.204.20]:5702 [dev] [4.1.1] Node creation failed
java.lang.NoSuchMethodError: com.hazelcast.internal.serialization.impl.ArrayDataSerializableFactory.<init>([Lcom/hazelcast/util/ConstructorFunction;)V
	at com.hazelcast.mapreduce.aggregation.impl.AggregationsDataSerializerHook.createFactory(AggregationsDataSerializerHook.java:432)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.<init>(DataSerializableSerializer.java:68)
	at com.hazelcast.internal.serialization.impl.SerializationServiceV1.<init>(SerializationServiceV1.java:145)
	at com.hazelcast.internal.serialization.impl.SerializationServiceV1$Builder.build(SerializationServiceV1.java:405)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.createSerializationService(DefaultSerializationServiceBuilder.java:300)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:236)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:55)
	at com.hazelcast.instance.impl.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:301)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:251)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
	at be.uclouvain.aptitude.test.SimpleAgent.$behaviorUnit$Initialize$0(SimpleAgent.java:22)
	at be.uclouvain.aptitude.test.SimpleAgent.lambda$0(SimpleAgent.java:31)
	at io.janusproject.kernel.bic.internaleventdispatching.AgentInternalEventsDispatcher$1.run(AgentInternalEventsDispatcher.java:295)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Describe the solution you'd like**
I may be wring but I assume that the problem is that somehow that Hazelcast 4 is not yet supported. I first thought the problem came from Hazelcast side, but as it is very simple code and it was released several months ago, this now seems very unlikely and I found no such errors on the internet.

So that would be nice to support Hazelcast 4 in a next version. If you have any other clew, I'm all ears of course!

**Describe alternatives you've considered**
I tried instantiating Hazelcast from a java class instead and get the instance from a SARL class, but I got the same exception so I guess it is related to SARL context.

So at the moment I moved back my code to target Hazelcast 3.12.12.

**Additional context**
I'm using SARL 10.1 with JDK 11.0.7 on Windows 10 64 bits

**Comment by gallandarakhneorg** [comment] 2021-02-10 12:56
It seems that there is different versions of Hazelcast used in the two cases.

Are you using Maven for building your project? In this case, you could force the version of Hazelcast in your `pom.xml` file.

If you are not using Maven (but using a simple SARL project), then SARL run-time libraries are added to the class path on-the-fly when you launch your application (The run-time libraries replace the SARL libraries in the project definition). The run-time libraries includes an hard-coded version of Hazelcast. You may have to change the order of the libraries in your project for having first the Jar files you have added by hand (the lastest version of Hazelcast) before the SARL libraries.

I assume that you launch your application with "SARL Agent" or "SARL Application" launch configurations.

**Comment by JonathanSamelson** [comment] 2021-02-10 14:27
I'm actually using Maven. In both cases I used the same project where I had the version 4.1.1 in my `pom.xml`. 

For the sample Java code I used Run as > Java Application whereas for the SARL I launched a Java Application using a run configuration (with io.sarl.bootstrap.SRE as the main class). This seems to be the only difference, except if the generated java code is actually the problem.

**Comment by gallandarakhneorg** [comment] 2021-02-10 14:56
There is no difference between Java and SARL regarding the access to the class files into the classpath, since SARL code is transformed to Java code before compiling to binary code. And becasue you are using "Run As Java Application" for both cases, the classpath should be the same for the both applications (assuming the two code are in the same project, otherwise, you have to double check that the two projects have exactly the same definition).

I saw a difference between your two code: in the SARL code you create an Hazelcast instance without argument.
Is it should be?

```sarl
var hcInstance = Hazelcast.newHazelcastInstance(hcConfig)
```

**Comment by gallandarakhneorg** [comment] 2021-02-10 15:01
The problem may be due to the fact that SARL `0.10.1` embeds Hazelcast in order to set up the network between the Janus nodes. It seems that there is some conflict between the two versions of Hazelcast.

If you plan to start an Hazelcast instance from within your agents, I think it is better to avoid the SARL run-time environment to start its own Hazelcast instance. Indeed, only one instance of Hazelcast is created per instance of Java virtual machine.

So that, I recommend to disable the networking feature of the SARL run-time environment by passing `--offline` as application command-line argument (into the Eclipse launch configuration).

Please indicate to us if there is a diffrence of behavior.

**Comment by JonathanSamelson** [comment] 2021-02-10 17:06
> I saw a difference between your two code: in the SARL code you create an Hazelcast instance without argument.
> Is it should be?
> 
> ```
> var hcInstance = Hazelcast.newHazelcastInstance(hcConfig)
> ```

Yes, I did several tests and I forgot to change this line, but it results the same with or without a config file.

>So that, I recommend to disable the networking feature of the SARL run-time environment by passing --offline as application command-line argument (into the Eclipse launch configuration).

>Please indicate to us if there is a diffrence of behavior.

![image](https://user-images.githubusercontent.com/19322574/107544192-44657e00-6bca-11eb-99c3-e2b5025e53ef.png)

So I added this to the program argument. Unfortunately, I obtain the same behavior.

**Comment by gallandarakhneorg** [comment] 2021-02-10 17:42
The `--offline` argument does not works when you launch an application using [SRE.main()].(https://github.com/sarl/sarl/blob/814788b81629cff3fb453f7433cb1eef4307c596/main/coreplugins/io.sarl.lang.core/src/io/sarl/bootstrap/SRE.java#L153)
Indeed, all the arguments are given to the launched agent, not to the SARL run-time environment.

If I understood well your previous messages, your're using `SRE.main()`.

In order to make a quick test, could you use the following main function:
```sarl
class MyMain {
    static def main(args : String[]) : void {
      val type = Class::forName(args.get(0)) as Class<? extends Agent>
      val bs = SRE::bootstrap
      bs.offline = true
      bs.startAgent(type)
    }
}
```

**Comment by JonathanSamelson** [comment] 2021-02-11 10:30
Indeed, I was using `SRE.main()`. I changed the main class for this one and give my SimpleAgent as argument but I still get the same stacktrace :(

**Comment by gallandarakhneorg** [comment] 2021-02-11 10:54
Ok; I will drawngrade my version of SARL and try to reproduce the issue from my side.

**Comment by JonathanSamelson** [comment] 2021-02-11 11:19
Thank you for your help and time!
If you know it would work well with the current version and I can also upgrade mine, but I had some issues a few months ago with 0.11 and my JDK, but this is probably solved ever since.

**Comment by gallandarakhneorg** [comment] 2021-02-11 16:11
Version 0.12 will be released in May 2021. Hazelcast is not any more included by default. It is inside a plugin that could be easily plugged in/out from your project.
I think it is preferable for you to skip 0.11 if you have encountered issues with it.

**Closed** 2021-04-13 12:50 UTC
Labels: 2 - In progress, SARL Runtime Environment, enhancement
