### ISSUE TITLE
Cannot use @Accessors: Type Accessors cannot be resolved to an annotation type.

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#865] opened 2018-09-28 13:22 UTC
**Describe the bug**

ECLIPSE does not allow me to use the @Accessors annotation

see screenshot below

**To Reproduce**

See screenshot below, just put @Accesssors var i : int

**Expected behavior**

Should get getters and setters well.

**Screenshots**

![image](https://user-images.githubusercontent.com/2368384/46210760-fa6efb00-c374-11e8-9a78-4caac392ac0f.png)

**System configuration:**
-- SARL version:	
-- SARL compiler:	
-  - [] Eclipse compiler without Maven	
-  - [X ] Eclipse compiler with Maven	
-  - [ ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name):	
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Linux 32bits	
-  - [ ] Windows 64bits	
-  - [ ] Windows 32bits	
-  - [ ] MacOS 64bits	

**Additional context**

**Comment by gallandarakhneorg** [comment] 2018-10-01 11:12
I cannot reproduce this issue.
Could you provide the dependency definition in your `pom.xml`file?

**Comment by ssardina** [comment] 2018-10-01 11:21
Here is my pom.xml, I did not know it had to do with that in my pom (I
thought SARL eclipse will come with everything needed).

I just noticed that ECLIPSE suggests me to add this import:

import org.eclipse.xtend.lib.annotations.Accessors


<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="
http://maven.apache.org/POM/4.0.0
http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>com.github.ssardina-research</groupId>

<artifactId>sarl-prolog-cap</artifactId>
<version>2.6.${env.SARL_VERSION}</version>

    <name>SARL Capacity for SWI Prolog Connectivity</name>
    <url>https://bitbucket.org/ssardina-research/sarl-prolog-cap</url>
    <description>
    Capacities and Skills for SARL to connect to SWI Prolog system.
Relies on JPL (https://jpl7.org/) and Mochalog (
https://github.com/ssardina/mochalog)
</description>

  <developers>
    <developer>
      <name>Sebastian Sardina</name>
      <email>ssardina@gmail.com</email>
      <organization>ssardina-research</organization>
      <organizationUrl>https://bitbucket.org/ssardina-research/
</organizationUrl>
    </developer>
  </developers>

  <licenses>
    <license>
      <name>GNU General Public License, Version 3.0</name>
      <url>https://www.gnu.org/licenses/gpl-3.0.en.html</url>
    </license>
  </licenses>

    <properties>
        
        <sarl.version>${env.SARL_VERSION}</sarl.version>

        
        <janus.version>2.${sarl.version}</janus.version>

        
        <compiler.level>1.8</compiler.level>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <dependencies>
        
        <dependency>
            <groupId>io.janusproject</groupId>
            <artifactId>io.janusproject.kernel</artifactId>
            <version>${janus.version}</version>
        </dependency>

        
        
        <dependency>
            <groupId>com.github.ssardina</groupId>
            <artifactId>mochalog</artifactId>
            <version>5aed56a</version>
        </dependency>


<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.7</version>
</dependency>


        <dependency>
          <groupId>junit</groupId>
          <artifactId>junit</artifactId>
          <version>4.12</version>
          <scope>test</scope>
</dependency>


        <dependency>
        <groupId>com.github.ssardina-research</groupId>
        <artifactId>packages-jpl</artifactId>
        <version>ssardina-devel</version>
        </dependency>
    </dependencies>

<repositories>
        
  <repository>
    <id>io.sarl-maven</id>
    <name>SARL Snapshots</name>
    <url>http://maven.sarl.io/</url>
  </repository>

        
        <repository>
            <id>jitpack.io</id>
            <name>JitPack Repository</name>
            <url>https://jitpack.io</url>
        </repository>
</repositories>
<pluginRepositories>
  <pluginRepository>
    <id>io.sarl-maven</id>
    <name>SARL Snapshots</name>
    <url>http://maven.sarl.io/</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </pluginRepository>
</pluginRepositories>





    
    <build>
  <resources>
               <resource>
                    <directory>src/main/sarl</directory>
                    <filtering>false</filtering>
                </resource>
                <resource>
                    <directory>src/main/java</directory>
                    <filtering>false</filtering>
                </resource>
          </resources>


        <plugins>
            <plugin>
                
                
                <groupId>io.sarl.maven</groupId>
                <artifactId>sarl-maven-plugin</artifactId>
                <version>${sarl.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <source>${compiler.level}</source>
                    <target>${compiler.level}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>


           
       <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-source-plugin</artifactId>
              <executions>
                    <execution>
                          <id>attach-sources</id>
                           <goals>
                               <goal>jar</goal>
                           </goals>
                    </execution>
              </executions>
       </plugin>


            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
                    <systemPropertyVariables>
                        <propertyName>java.library.path</propertyName>

<buildDirectory>/usr/lib/swi-prolog/lib/amd64/</buildDirectory>
                    </systemPropertyVariables>
                </configuration>
            </plugin>


            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <configuration>
                
                  <mainClass>BootTestAgt</mainClass>
                </configuration>
            </plugin>



</plugins>

    </build>

</project>

**Comment by gallandarakhneorg** [comment] 2018-10-01 12:10
Thxs. I do not see any problem.
The annotation is indeed `org.eclipse.xtend.lib.annotations.Accessors`, and it should be imported.
Whe nthe SARL compiler report an error of type "Accessors is not an annotation", it means that it has not recovering the correct Java definition of `Accessors` from the classpath.
You have to be sure that the imported type is the one mantioned above, and it is provided by a Xtext library with version `2.15.0` (assuming you are using a 0.8.x version of SARL).
The fact is that when you have defined a Maven project, a part of the libraries are not given by Eclipse itself but by the Maven dependencies.

**Comment by gallandarakhneorg** [comment] 2018-10-01 12:16
Is the compilation works fine from the command-line?

**Comment by ssardina** [comment] 2018-10-02 08:41
Hi @gallandarakhneorg . Nope, it does not work on command line either. The error I get is:

`[ERROR] Forbidden annotation to an agent-oriented feature. [/home/ssardina/git/soft/agents/SARL/sarl-prolog-cap.git/src/main/sarl/io/sarl/extras/TestAgt_SWIJPL_MT.sarl:52]
`

My code is simple:

```
agent TestAgt_SWIJPL_MT {
	uses Logging
	uses KB_Prolog	

	@Accessors 
	val testFile = "src/test/resources/testKB_MT.pl"

```
 
Same error message on ECLIPSE.

Using 0.7.2 version though, have not yet tried 0.8.2
THis is the import I have:

`import org.eclipse.xtend.lib.annotations.Accessors
`

**Comment by gallandarakhneorg** [comment] 2018-10-02 09:28
But the error "Forbidden annotation to an agent-oriented feature." is not the same as the first you have mentionned above.
Could you try the new version of SARL 0.8.2, and try to reproduce the error in Eclipse.
I tried without success.

**Comment by ssardina** [comment] 2018-10-02 22:54
You are totally right. Initially I tried in a standard class file. It now
works on 0.8.2

So @Accessors is only for Java-sarl files right then? Not for argents,
behaviors, or skills... Good.

**Comment by gallandarakhneorg** [comment] 2018-10-03 04:05
Great!
I close this issue, and open Issue #868 for discussing if it is pertinent to enable `@Accessors` to agent-oriented type declarations.

**Closed by gallandarakhneorg** 2018-10-03 04:05 UTC
Labels: 2 - Working, Eclipse, Language & Compiler, bug
