### ISSUE TITLE
Janus SRE not in IDE Eclipse (0.11.0)

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#1057] opened 2021-02-08 00:46 UTC
**Describe the bug**

The ECLIPSE IDE for 0.11.0 does not seem to grab the SRE, and I cannot add it manually:

![image](https://user-images.githubusercontent.com/2368384/107164492-5ba63f00-6a03-11eb-8a4e-a23734b8634d.png)

**Expected behavior**

The IDE will pick up the SRE automatically in previous versions

**Screenshots**

**System configuration:**
-- SARL version:	0.11.0
-- SARL compiler:	
-  - [] Eclipse compiler without Maven	
-  - [X ] Eclipse compiler with Maven	
-  - [ ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name):	OpenJDK 11
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Windows 64bits	
-  - [ ] MacOS 64bits

**Comment by ssardina** [comment] 2021-02-08 10:59
This is the most pressing one I would say, at least for me if I want to give it to my class to develop with ECLIPSE (which is often preferred for many students)

I am curious if this is an issue of the IDE itself or something wrong on my side...

If there is any work-around, it would be good enough for now.. But I couldn't add the SRE manually.

**Comment by gallandarakhneorg** [comment] 2021-02-08 12:15
I could reproduce the problem with SARL 0.11 and Java 11. Your issue is a duplicate of Issue #1012.
The problem seems to be solved in SARL 0.12 (under development).

Two ways to fix quickly this issue:
1) Wait for the release of 0.12 (planned in April 2021).
2) Downgrade to Java 1.8 or simply launch the SARL IDE with Java 1.8 (see the file `eclipse-sarl.ini` below for forcing this by hand, line `-vm` and following):

```
-startup
plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.1200.v20200508-1552
-vm
/usr/lib/jvm/java-8-openjdk-amd64/bin
-vmargs
-Xms256m
-Xmx1g
```

**Closed** 2021-02-08 12:16 UTC
Labels: 1 - Ready to do, Eclipse, bug, duplicate

**Comment by ssardina** [comment] 2021-02-09 05:19
It works, thanks!  The SRE is there when I start ECLIPSE with Java 8.

One thing though: I also had to change the JRE in the IDE to Java 8, or otherwise it does not run the app:

**Comment by gallandarakhneorg** [comment] 2021-02-09 07:26
Yes. I closed the issue based on your previous messages.

Eclispe is anoying because stores a lot of configuration elements in the project's files that are not updated dynamically. That's why, sometimes, it is better to remove the project in Eclipse, delete the Eclipse file in the project folder, and import again the project.
