### ISSUE TITLE
No agent booting via Java

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#1061] opened 2021-02-14 03:17 UTC
**Describe the bug**

I can run my application via `maven exec:java` because it starts a Java class which will create an agent.

However, I cannot anymore in 0.11.0 start an agent directly using Java + SRE's Booting service.

Even trying to do what is stated in http://www.sarl.io/docs/official/gettingstarted/RunSARLAgentCLI.html gives error:

```
$ java -cp target/agtcity-sarl-base-4.5.0.11.0-jar-with-dependencies.jar io.sarl.sre.boot.Boot --help
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/ssardina/git/soft/agents/MAC-AgtCity/2018-rmit/agtcity-sarl-base.git/target/agtcity-sarl-base-4.5.0.11.0-jar-with-dependencies.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Could not find a suitable constructor in io.sarl.sre.boot.commands.RunSingleAgentCommand. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at io.sarl.sre.boot.commands.RunSingleAgentCommand.class(RunSingleAgentCommand.java:60)
  at io.bootique.BQCoreModuleExtender.setDefaultCommand(BQCoreModuleExtender.java:95)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at io.bootique.Bootique.createInjector(Bootique.java:472)
	at io.bootique.Bootique.createRuntime(Bootique.java:330)
	at io.sarl.sre.boot.SreMain.createRuntime(SreMain.java:232)
	at io.sarl.sre.boot.SreMain.ensureBootiqueRuntimeInstance(SreMain.java:238)
	at io.sarl.sre.boot.SreMain.runSRE(SreMain.java:253)
	at io.sarl.sre.boot.Boot.main(Boot.java:84)
```

When I try to boot an agent:

```bash
$ java -cp target/agtcity-sarl-base-4.5.0.11.0-jar-with-dependencies.jar io.sarl.sre.boot.Boot au.edu.rmit.agtgrp.agtcity.sarl.agents.dummy.SuperSingleAgent
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/ssardina/git/soft/agents/MAC-AgtCity/2018-rmit/agtcity-sarl-base.git/target/agtcity-sarl-base-4.5.0.11.0-jar-with-dependencies.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Could not find a suitable constructor in io.sarl.sre.boot.commands.RunSingleAgentCommand. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at io.sarl.sre.boot.commands.RunSingleAgentCommand.class(RunSingleAgentCommand.java:60)
  at io.bootique.BQCoreModuleExtender.setDefaultCommand(BQCoreModuleExtender.java:95)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at io.bootique.Bootique.createInjector(Bootique.java:472)
	at io.bootique.Bootique.createRuntime(Bootique.java:330)
	at io.sarl.sre.boot.SreMain.createRuntime(SreMain.java:232)
	at io.sarl.sre.boot.SreMain.ensureBootiqueRuntimeInstance(SreMain.java:238)
	at io.sarl.sre.boot.SreMain.runSRE(SreMain.java:253)
	at io.sarl.sre.boot.Boot.main(Boot.java:84)
```

**System configuration:**
-- SARL version:	0.11.0
-- SARL compiler:	
-  - [] Eclipse compiler without Maven	
-  - [ ] Eclipse compiler with Maven	
-  - [ ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name):	
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Windows 64bits	
-  - [ ] MacOS 64bits	

**Additional context**

**Comment by gallandarakhneorg** [comment] 2021-02-14 16:12
## Cause

The cause of the problem is the way how you have created the jar file with all the dependencies inside.
Several service definitions of SARL/Janus services are not correctly included into the "with-full-dependencies" jar file.

## Background

Since version SARL 0.11, we are using the Java feature of service (i.e. SARL plugins are defined as services).
According to the Java specification, each service must be declared into a dedicated file in the folder `META-INF/services`.

## Problem Cause

When creating the jar file with `maven-assembly-plugin`, the content of the `META-INF/services` folders from the different included jar files are not correctly merged into the jar file with all the dependencies.

## Fixing the problem

You have to force `maven-assembly-plugin` to use a specific merging capability for the `META-INF/services` folders.

**Only the version 3.3.0 (or higher) of maven-assembly-plugin provides this capability**

Let the file `with-all-dependencies.xml`, that defines how the assembly is created, must contains the following tags:
```xml
  <containerDescriptorHandlers>
		<!-- Merge service description's files in a proper way -->
		<containerDescriptorHandler>
			<handlerName>metaInf-services</handlerName>
		</containerDescriptorHandler>
  </containerDescriptorHandlers>
```

## Action inside the SARL repository

The official documentation will provide the typical definition for the `maven-assembly-plugin`.

**Closed** 2021-02-14 16:59 UTC
Labels: 2 - In progress, Documentation, FAQ, bug

**Comment by ssardina** [comment] 2021-02-14 20:08
Ahh OK, that would explain it. I must be using plugins that are not included in the JAR. All I include is JANUS (3.x now):

```xml
            <groupId>io.janusproject</groupId>
            <artifactId>io.janusproject.kernel</artifactId>
            <version>${janus.version}</version>
```

Sorry, didn't know whether this would go here in the issue tracker or in the Google forum...

While one can run the system with Maven, for completeness, indeed would be good to have a guide on how those dependencies need to be packed into the JAR to have a plain JAR file with all. Maybe also what "services" SARL has available? (before I had assumed we do not need to know that, but given this I guess it is important)

Thanks!!

Thanks!

**Comment by gallandarakhneorg** [comment] 2021-02-14 20:38
You're dependency is ok. I provide to you a typical "simple" pom file:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>mygroupId</groupId>
    <artifactId>MySarlProject</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <properties>
        <target.jdk.version>1.8</target.jdk.version>
        <sarl.version>0.11.0</sarl.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <cliRunnerMainClass>io.sarl.sre.boot.Boot</cliRunnerMainClass>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.janusproject</groupId>
            <artifactId>io.janusproject.kernel</artifactId>
            <version>3.${sarl.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${target.jdk.version}</source>
                    <target>${target.jdk.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>io.sarl.maven</groupId>
                <artifactId>sarl-maven-plugin</artifactId>
                <version>${sarl.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <source>${target.jdk.version}</source>
                    <target>${target.jdk.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
            <plugin>
                <!--  to create a jar with all dependencies  -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <id>make-assembly-with-deps</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>with-dependencies.xml</descriptor>
                            </descriptors>
                            <archive>
                                <manifest>
                                    <mainClass>${cliRunnerMainClass}</mainClass>
                                </manifest>
                                <manifestEntries>
                                    <Automatic-Module-Name>${project.artifactId}</Automatic-Module-Name>
                                </manifestEntries>
                            </archive>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by ssardina** [comment] 2021-02-15 01:59
Gracias! I tried it and complains the xml file is missing:

```bash
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single (make-assembly-with-deps) on project agtcity-sarl-base: Error reading assemblies: Error locating assembly descriptor: with-dependencies.xml
```

Of course you would know about this... How would that file look like..

**Comment by gallandarakhneorg** [comment] 2021-02-15 08:07
Dear @ssardina.
From the SARL documentation, the file may be created into the same folder as the `pom.xml` and looks like:

```xml
<assembly xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.0"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.0 http://maven.apache.org/xsd/assembly-1.1.0.xsd">
  <id>with-dependencies</id>
  <formats>
    <format>jar</format>
  </formats>
  <includeBaseDirectory>false</includeBaseDirectory>
  <dependencySets>
    <dependencySet>
      <unpack>true</unpack>
      <scope>runtime</scope>
    </dependencySet>
  </dependencySets>
  <containerDescriptorHandlers>
    <!-- Merge service description's files in a proper way -->
    <containerDescriptorHandler>
      <handlerName>metaInf-services</handlerName>
    </containerDescriptorHandler>
  </containerDescriptorHandlers>
</assembly>
```

**Comment by ssardina** [comment] 2021-02-15 21:58
Ohh it is there? Sorry, didn't find it. Somehow I quite often don t find things that are there. Not sure why, I still haven't figured out how to navigate the doc (which is very nice and clear) ... Thanks

**Comment by gallandarakhneorg** [comment] 2021-02-15 22:16
No problem; I have added it a couple of days ago based on your issue report :-)

**Comment by ssardina** [comment] 2021-02-16 00:59
ahhh OK so I was a bit useful then ;-) ha!

Just tested and it works! I can run the system via Java.
