### ISSUE TITLE
Cannot use emit function in the Initialize handler

### ISSUE THREAD

**Issue by gbasso** [sarl/sarl#861] opened 2018-09-24 16:32 UTC
**Bug description**
When calling the `emit` function in the `Initialize` handler, the message is not sent.

**To Reproduce**
Run this code:
```
import io.sarl.core.DefaultContextInteractions
import io.sarl.core.Initialize
import io.sarl.core.Lifecycle
import io.sarl.core.Logging

event Initialized
event CommitSuicide

agent EmptyAgent {
	uses Lifecycle, DefaultContextInteractions, Logging
	
	on Initialize {
		info("Empty-Init")
		emit(new Initialized)[it.UUID == occurrence.spawner]		
	}
	
	on CommitSuicide {
		info("Empty-Suicide")
		killMe
	}
}

agent BootAgent {
    uses Lifecycle, DefaultContextInteractions, Logging
    on Initialize {
    	info('Boot-Init')
		spawn(EmptyAgent)
    }
    
	on Initialized {
		info('Boot-Reception')
		emit(new CommitSuicide)
	}

	on CommitSuicide {
		info('Boot-Suicide')
		killMe
	}
}
```

**Expected behavior**
The `emit` function has to be able to send the message.

**System configuration:**
-- SARL version: 0.8.0
-- SARL compiler:	
-  - [x] Eclipse compiler without Maven

-- Java JDK version (with the manufacturer name):	
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

-- Operating System:	
-  - [x] Linux 64bits

**Comment by gallandarakhneorg** [comment] 2018-09-25 16:37
The bug is validated, and the location of the problem is found. Any event that is received by an agent during its initialization stage is buffered until the end of the initialization stage. Then, the buffered events are supposed to be fired into the agent. The problem is that the function for firing the buffered events was called when another event is received after the initialization stage. It means that the buffered events are not fired until a new event comes. Because of the highly parallel execution of the event handlers, the previous behavior causes freezes of the agents.

The problem is fixed by firing the buffered events as soon the `on Initilialize` is run. The patch will be available within a version 0.8.1 that will be release during the next couple of days.

**Closed** 2018-09-27 23:35 UTC
Labels: 2 - Working, SARL Runtime Environment, bug
