### ISSUE TITLE
Problem when renaming package using refactor

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#584] opened 2017-02-21 14:55 UTC
A small error when I was renaming a package initially named "io.sarl.demos.basic.inheritance" into "io.sarl.demos.inheritance"

I obtain that
```
package io.sarl.demos.inheritancert io.sarl.core.AgentKilled
import io.sarl.core.AgentSpawned
```

instead of

```
package io.sarl.demos.inheritance
import io.sarl.core.AgentKilled
import io.sarl.core.AgentSpawned
```

Same thing when i try to rename "io.sarl.demos.inheritance" into io.sarl.article.inheritance"

I obtain this
```
package io.sarl.articles.inheritancence
import io.sarl.core.AgentKilled
```

**Comment by gallandarakhneorg** [comment] 2017-02-22 09:35
Currently, only the package renaming from the package explorer is allowed. I will add the missed unit tests for this feature.

Renaming the package from the SARL editor will be fixed by Issue #585.

**Comment by gallandarakhneorg** [comment] 2017-02-23 19:04
I cannot reproduce the issue with unit tests, the product launched from Eclipse IDE, or the product launched from the command line.

**Closed by gallandarakhneorg** 2017-02-23 19:04 UTC
Labels: 2 - Working, bug, Eclipse, invalid
